/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.multiplicacionmartriz;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class Matrices extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Matrices.class.getName());

    /**
     * Creates new form Matrices
     */
    public Matrices() {
        initComponents();
    }

     private void txtTamanoKeyTyped(java.awt.event.KeyEvent evt) {
    char c = evt.getKeyChar();

    if (!Character.isDigit(c)) {
        evt.consume(); // No permite el carácter

        Toolkit.getDefaultToolkit().beep();

        JOptionPane.showMessageDialog(this,
                "Solo se permiten números.");
    }
}
private void validarTabla(javax.swing.JTable tabla) {

    tabla.getModel().addTableModelListener(e -> {

        int fila = e.getFirstRow();
        int columna = e.getColumn();

        Object valor = tabla.getValueAt(fila, columna);

        if (valor == null) return;

        try {

            Double.parseDouble(valor.toString());

        } catch (NumberFormatException ex) {

            tabla.setValueAt(null, fila, columna);

            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números");
        }
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatrizA = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatrizB = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnMultiplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tamaño de matriz");

        jTextField1.setToolTipText("Ingrese solo numeros");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel2.setText("Multiplicacion de matrices ");

        jLabel3.setText("Presione enter despues de inserta un numero");

        tblMatrizA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMatrizA);

        tblMatrizB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMatrizB);

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblResultado);

        btnMultiplicar.setText("Calcular");
        btnMultiplicar.addActionListener(this::btnMultiplicarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnMultiplicar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(btnMultiplicar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    int n = Integer.parseInt(jTextField1.getText());

    String[] columnas = new String[n + 1];

    columnas[0] = "";

    for (int i = 1; i <= n; i++) {
        columnas[i] = "C" + i;
    }

    DefaultTableModel modeloA = new DefaultTableModel(columnas, n) {
    @Override
    public boolean isCellEditable(int fila, int columna) {
        return columna != 0; // La columna F no se puede editar
        }
    };
    DefaultTableModel modeloB = new DefaultTableModel(columnas, n) {
    @Override
    public boolean isCellEditable(int fila, int columna) {
        return columna != 0; // La columna F no se puede editar
    }
};
    
    for (int i = 0; i < n; i++) {
        modeloA.setValueAt("F" + (i + 1), i, 0);
        modeloB.setValueAt("F" + (i + 1), i, 0);
    }

    tblMatrizA.setModel(modeloA);
    tblMatrizB.setModel(modeloB);

    validarTabla(tblMatrizA);
    validarTabla(tblMatrizB);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '\b') {
          evt.consume();
}
    }//GEN-LAST:event_jTextField1KeyTyped

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        
    int n = tblMatrizA.getRowCount();

    String[] columnas = new String[n + 1];
    columnas[0] = "";

    for (int i = 1; i <= n; i++) {
        columnas[i] = "C" + i;
    }

    DefaultTableModel modeloR = new DefaultTableModel(columnas, n);
    
    // Etiquetas F1, F2, F3...
    for (int i = 0; i < n; i++) {
        modeloR.setValueAt("F" + (i + 1), i, 0);
    }

    double[][] A = new double[n][n];
    double[][] B = new double[n][n];
    double[][] R = new double[n][n];

    // Leer Matriz A
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {

            Object valor = tblMatrizA.getValueAt(i, j + 1);

            if (valor == null || valor.toString().trim().isEmpty()) {
                valor = "0";
            }

            A[i][j] = Double.parseDouble(valor.toString());
        }
    }

    // Leer Matriz B
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {

            Object valor = tblMatrizB.getValueAt(i, j + 1);

            if (valor == null || valor.toString().trim().isEmpty()) {
                valor = "0";
            }

            B[i][j] = Double.parseDouble(valor.toString());
        }
    }

    // Multiplicación de matrices
    for (int i = 0; i < n; i++) {

        for (int j = 0; j < n; j++) {

            R[i][j] = 0;

            for (int k = 0; k < n; k++) {

                R[i][j] += A[i][k] * B[k][j];

            }
        }
    }

    // Mostrar resultado
    for (int i = 0; i < n; i++) {

        for (int j = 0; j < n; j++) {

            modeloR.setValueAt(R[i][j], i, j + 1);

        }
    }

    tblResultado.setModel(modeloR);
    TableRowSorter<DefaultTableModel> sorter =
        new TableRowSorter<>((DefaultTableModel) tblResultado.getModel());

tblResultado.setRowSorter(sorter);
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Matrices().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblMatrizA;
    private javax.swing.JTable tblMatrizB;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables
}


